# Project: Athenos
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = obj/Athenos_private.res
OBJ  = obj/main.o $(RES)
LINKOBJ  = obj/main.o $(RES)
LIBS =  -L"C:/Users/Mico_Ultrabook/Desktop/Developer Software/Dev-CppPortable/App/devcpp/lib" -mwindows  -g3 
INCS =  -I"C:/Users/Mico_Ultrabook/Desktop/Developer Software/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"C:/Users/Mico_Ultrabook/Desktop/Developer Software/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/Mico_Ultrabook/Desktop/Developer Software/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"C:/Users/Mico_Ultrabook/Desktop/Developer Software/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"C:/Users/Mico_Ultrabook/Desktop/Developer Software/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"C:/Users/Mico_Ultrabook/Desktop/Developer Software/Dev-CppPortable/App/devcpp/include" 
BIN  = bin/Athenos.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before bin/Athenos.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "bin\Athenos.exe" $(LIBS)

obj/main.o: main.cpp
	$(CPP) -c main.cpp -o obj/main.o $(CXXFLAGS)

obj/Athenos_private.res: Athenos_private.rc 
	$(WINDRES) -i Athenos_private.rc --input-format=rc -o obj/Athenos_private.res -O coff 
